# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc

script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. ; fi
   # On Linux Travis, we have several Pythons and need to take care to use the one that `python3` is.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DPYTHON_EXECUTABLE=`which python3` .. ; fi
  - make -j2
  - cd ../docs
  - pip3 install -r requirements.txt
  - make doctest
  - cd ../build 
  - make clean
  - cd .. 
  - rm -Rf build
dist: bionic
osx_image: xcode10.1
  
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
      
addons:
  apt:
    update: true
    packages:
      - python3
      - python3-dev
      - python3-pip
      - doxygen
  homebrew:
    packages:
      - libomp
      - doxygen
