# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libomp; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir build && cd build && cmake .. && make -j2 && make clean && cd .. && rm -Rf build; fi
  # On Linux Travis, we have several Pythons and need to take care to use the one that `python3` is.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir build && cd build && cmake -DPYTHON_EXECUTABLE=`which python3` .. && make -j2 && make clean && cd .. && rm -Rf build; fi

dist: bionic
osx_image: xcode10.1
  
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
      
addons:
  apt:
    update: true
    packages:
      - python3.7
      - python3.7-dev
