# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc

script:
  - mkdir build && cd build && cmake .. && make -j2
cache:
  ccache: true
  directories:
    - build
    - lib
    - bin

osx_image: xcode10.1
  
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
